### ISSUE TITLE
attempt to multiply with overflow

### ISSUE THREAD

**Issue by nlinker** [LinusU/rs-xorshift128plus#1]
I'm having an issue with running the following code:
```rust
use xorshift128plus::XorShift128Plus;
fn main() {
    let mut random = XorShift128Plus::from_u64(69);
    println!("{}", random.next());
}
```
It panics:
```
thread 'main' panicked at 'attempt to multiply with overflow', /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/xorshift128plus-0.1.1/src/lib.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
   ...
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: xorshift128plus::splitmix64
             at /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/xorshift128plus-0.1.1/src/lib.rs:16
   ...
```
The information about my system:
*OS*: Ubuntu 18.04.2 LTS x64
*Rust*: rustc 1.37.0-nightly (0dc9e9c10 2019-06-15)
*crate*: xorshift128plus = "0.1.1"

Thanks!

**Comment by LinusU** [comment]
Sorry for the suuuuuuper late reply 🙈 

The problem is that I haven't properly used wrapping arithmetic. We can either use `std::num::Wrapping`, or use the `wrapping_*` methods on `u64`.

Open to pull requests ☺️
